export interface FlutterFile {
  name: string;
  path: string;
  language: string;
  content: string;
}

export const FLUTTER_FILES: FlutterFile[] = [
  {
    name: "pubspec.yaml",
    path: "pubspec.yaml",
    language: "yaml",
    content: `name: daily_expense_pro
description: A Refined Premium Fintech Expense Tracker & Budget Manager connected to Firebase.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core and Services
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_messaging: ^14.7.5

  # State Management & Utilities
  provider: ^6.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  fl_chart: ^0.66.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
`
  },
  {
    name: "main.dart",
    path: "lib/main.dart",
    language: "dart",
    content: `import 'package:flutter/material';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart';
import 'services/auth_service.dart';
import 'pages/login_page.dart';
import 'pages/dashboard_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase using options generated by flutterfire configure
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
      ],
      child: const DailyExpenseApp(),
    ),
  );
}

class DailyExpenseApp extends StatelessWidget {
  const DailyExpenseApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Daily Expense Pro',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.system,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF0D9488), // Teal primary
          brightness: Brightness.light,
          background: const Color(0xFFF3F4F6),
        ),
        textTheme: GoogleFonts.interTextTheme(Theme.of(context).textTheme),
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF0D9488),
          brightness: Brightness.dark,
          background: const Color(0xFF0F172A), // Slate-900
        ),
        textTheme: GoogleFonts.interTextTheme(Theme.of(context).darkTextTheme),
      ),
      home: const AuthGate(),
    );
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context);

    // StreamBuilder listens to real Firebase user auth state changes
    return StreamBuilder(
      stream: authService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(color: Color(0xFF0D9488)),
            ),
          );
        }
        
        if (snapshot.hasData) {
          return const DashboardPage();
        }
        
        return const LoginPage();
      },
    );
  }
}
`
  },
  {
    name: "firebase_options.dart",
    path: "lib/firebase_options.dart",
    language: "dart",
    content: `// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with [Firebase.initializeApp].
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-EXAMPLE_KEY_DO_NOT_EXPOSE_SECRET',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'daily-expense-pro-firebase',
    authDomain: 'daily-expense-pro-firebase.firebaseapp.com',
    storageBucket: 'daily-expense-pro-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EXAMPLE_ANDROID_KEY',
    appId: '1:123456789:android:987654321',
    messagingSenderId: '123456789',
    projectId: 'daily-expense-pro-firebase',
    storageBucket: 'daily-expense-pro-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-EXAMPLE_IOS_KEY',
    appId: '1:123456789:ios:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'daily-expense-pro-firebase',
    storageBucket: 'daily-expense-pro-firebase.appspot.com',
    iosBundleId: 'com.seenu.dailyexpensepro',
  );
}
`
  },
  {
    name: "auth_service.dart",
    path: "lib/services/auth_service.dart",
    language: "dart",
    content: `import 'package:flutter/material';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AuthService with ChangeNotifier {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Stream of Auth State Changes
  Stream<User?> get authStateChanges => _auth.authStateChanges();

  // Get current user
  User? get currentUser => _auth.currentUser;

  // Sign Up with Email and Password
  Future<String?> signUpWithEmail({
    required String email,
    required String password,
    required String displayName,
  }) async {
    try {
      // 1. Create firebase user credentials
      UserCredential credential = await _auth.createUserWithEmailAndPassword(
        email: email.trim(),
        password: password.trim(),
      );

      // 2. Update user profile display name
      if (credential.user != null) {
        await credential.user!.updateDisplayName(displayName);
        
        // 3. Store user private data safely in isolated Firestore split-collection
        await _db.collection('users').doc(credential.user!.uid).set({
          'uid': credential.user!.uid,
          'email': email.trim(),
          'displayName': displayName,
          'createdAt': FieldValue.serverTimestamp(),
          'dailyBudgetLimit': 150.00,
          'monthlyBudgetLimit': 2000.00,
          'currency': 'USD',
        });
        
        // Create initial placeholder/demo transaction
        await _db.collection('users').doc(credential.user!.uid).collection('transactions').add({
          'merchant': 'Welcome Gift Credit',
          'amount': 25.00,
          'category': 'other',
          'isExpense': false,
          'timestamp': FieldValue.serverTimestamp(),
          'date': DateTime.now().toIso8601String().substring(0, 10),
        });
      }
      return null; // Success
    } on FirebaseAuthException catch (e) {
      return e.message ?? "An authentication error occurred.";
    } catch (e) {
      return e.toString();
    }
  }

  // Sign In with Email and Password
  Future<String?> signInWithEmail({
    required String email,
    required String password,
  }) async {
    try {
      await _auth.signInWithEmailAndPassword(
        email: email.trim(),
        password: password.trim(),
      );
      return null; // Success
    } on FirebaseAuthException catch (e) {
      return e.message ?? "Incorrect email or password.";
    } catch (e) {
      return e.toString();
    }
  }

  // Sign Out
  Future<void> signOut() async {
    await _auth.signOut();
    notifyListeners();
  }

  // Password Reset
  Future<String?> resetPassword(String email) async {
    try {
      await _auth.sendPasswordResetEmail(email: email.trim());
      return null;
    } on FirebaseAuthException catch (e) {
      return e.message;
    } catch (e) {
      return e.toString();
    }
  }
}
`
  },
  {
    name: "dashboard_page.dart",
    path: "lib/pages/dashboard_page.dart",
    language: "dart",
    content: `import 'package:flutter/material';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../services/auth_service.dart';
import '../widgets/add_transaction_dialog.dart';
import '../widgets/notifications_panel.dart';
import 'profile_page.dart';

class DashboardPage extends StatefulWidget {
  const DashboardPage({super.key});

  @override
  State<DashboardPage> createState() => _DashboardPageState();
}

class _DashboardPageState extends State<DashboardPage> {
  String _selectedCategoryFilter = 'all';

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context, listen: false);
    final uid = authService.currentUser?.uid ?? '';
    final String userDisplayName = authService.currentUser?.displayName ?? 'Seenu';

    return Scaffold(
      backgroundColor: Theme.of(context).brightness == Brightness.dark
          ? const Color(0xFF0F172A)
          : const Color(0xFFF3F4F6),
      appBar: AppBar(
        title: Row(
          children: [
            GestureDetector(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const ProfilePage()),
                );
              },
              child: CircleAvatar(
                backgroundColor: const Color(0xFF0D9488),
                child: Text(
                  userDisplayName.isNotEmpty ? userDisplayName[0].toUpperCase() : 'S',
                  style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                ),
              ),
            ),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Hi, Welcome 👋', style: TextStyle(fontSize: 12, color: Colors.grey)),
                Text(
                  userDisplayName,
                  style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                ),
              ],
            ),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.person_outline),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => const ProfilePage()),
              );
            },
          ),
          IconButton(
            icon: const Badge(
              label: Text('2'),
              child: Icon(Icons.notifications_outlined),
            ),
            onPressed: () {
              showModalBottomSheet(
                context: context,
                isScrollControlled: true,
                backgroundColor: Colors.transparent,
                builder: (context) => const NotificationsPanel(),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () => authService.signOut(),
          ),
        ],
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: FirebaseFirestore.instance
            .collection('users')
            .doc(uid)
            .collection('transactions')
            .orderBy('timestamp', descending: true)
            .snapshots(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator(color: Color(0xFF0D9488)));
          }

          final docs = snapshot.data?.docs ?? [];
          double totalSpent = 0.0;
          double totalIncome = 0.0;
          
          for (var doc in docs) {
            final data = doc.data() as Map<String, dynamic>;
            final amount = (data['amount'] ?? 0).toDouble();
            final isExpense = data['isExpense'] ?? true;
            if (isExpense) {
              totalSpent += amount;
            } else {
              totalIncome += amount;
            }
          }

          double remainingBudget = 2000.0 - totalSpent;
          double budgetProgress = (totalSpent / 2000.0).clamp(0.0, 1.0);

          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            child: ListView(
              physics: const BouncingScrollPhysics(),
              children: [
                const SizedBox(height: 16),
                
                // TODAY SPENT CARD
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(24),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.04),
                        blurRadius: 10,
                        offset: const Offset(0, 4),
                      )
                    ],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        "MONTHLY SPENT TOTAL",
                        style: TextStyle(
                          fontSize: 11,
                          fontWeight: FontWeight.extrabold,
                          color: Colors.grey,
                          letterSpacing: 1.2,
                        ),
                      ),
                      const SizedBox(height: 6),
                      Text(
                        '\\$\${totalSpent.toStringAsFixed(2)}',
                        style: const TextStyle(
                          fontSize: 32,
                          fontWeight: FontWeight.black,
                          color: Color(0xFF1E293B),
                        ),
                      ),
                      const SizedBox(height: 8),
                      // Progress Bar
                      LinearProgressIndicator(
                        value: budgetProgress,
                        backgroundColor: Colors.teal.withOpacity(0.1),
                        color: const Color(0xFF0D9488),
                        minHeight: 8,
                        borderRadius: BorderRadius.circular(4),
                      ),
                      const SizedBox(height: 8),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.between,
                        children: [
                          Text(
                            'Budget limit: \\$2,000.00',
                            style: const TextStyle(fontSize: 11, color: Colors.grey),
                          ),
                          Text(
                            '\${(budgetProgress * 100).toStringAsFixed(0)}% Spent',
                            style: const TextStyle(
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF0D9488),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                
                const SizedBox(height: 16),
                
                // INCOME VS EXPENSES SPLIT OVERVIEW
                Row(
                  children: [
                    Expanded(
                      child: _buildSplitCard(
                        context,
                        title: "Income",
                        amount: totalIncome,
                        icon: Icons.trending_up,
                        iconColor: Colors.emerald,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: _buildSplitCard(
                        context,
                        title: "Expenses",
                        amount: totalSpent,
                        icon: Icons.trending_down,
                        iconColor: Colors.rose,
                      ),
                    ),
                  ],
                ),
                
                const SizedBox(height: 24),
                
                // RECENT TRANSACTIONS HEADER
                const Row(
                  mainAxisAlignment: MainAxisAlignment.between,
                  children: [
                    Text(
                      "Recent Transactions",
                      style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                    ),
                    Text(
                      "Realtime Sync",
                      style: TextStyle(fontSize: 12, color: Colors.grey),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                
                // TRANSACTIONS LIST
                docs.isEmpty
                    ? Container(
                        padding: const EdgeInsets.all(32),
                        alignment: Alignment.center,
                        child: const Column(
                          children: [
                            Icon(Icons.receipt_long_outlined, size: 48, color: Colors.grey),
                            SizedBox(height: 8),
                            Text("No transactions saved yet", style: TextStyle(fontWeight: FontWeight.bold, color: Colors.grey)),
                          ],
                        ),
                      )
                    : Column(
                        children: docs.map((doc) {
                          final data = doc.data() as Map<String, dynamic>;
                          final merchant = data['merchant'] ?? 'Unknown';
                          final amount = (data['amount'] ?? 0.0).toDouble();
                          final category = data['category'] ?? 'other';
                          final isExpense = data['isExpense'] ?? true;
                          
                          return Card(
                            elevation: 0,
                            margin: const EdgeInsets.only(bottom: 8),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(16),
                              side: BorderSide(color: Colors.grey.withOpacity(0.1)),
                            ),
                            child: ListTile(
                              leading: CircleAvatar(
                                backgroundColor: const Color(0xFF0D9488).withOpacity(0.1),
                                child: Icon(
                                  isExpense ? Icons.shopping_bag_outlined : Icons.monetization_on_outlined,
                                  color: const Color(0xFF0D9488),
                                ),
                              ),
                              title: Text(merchant, style: const TextStyle(fontWeight: FontWeight.bold)),
                              subtitle: Text(category.toUpperCase(), style: const TextStyle(fontSize: 11)),
                              trailing: Text(
                                '\${isExpense ? "-" : "+"}\\$\${amount.toStringAsFixed(2)}',
                                style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: isExpense ? Colors.black : Colors.emerald,
                                ),
                              ),
                            ),
                          );
                        }).toList(),
                      ),
                const SizedBox(height: 100),
              ],
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showDialog(
            context: context,
            builder: (context) => AddTransactionDialog(userId: uid),
          );
        },
        backgroundColor: const Color(0xFF0D9488),
        child: const Icon(Icons.add, color: Colors.white, size: 28),
      ),
    );
  }

  Widget _buildSplitCard(
    BuildContext context, {
    required String title,
    required double amount,
    required IconData icon,
    required Color iconColor,
  }) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.solid,
        borderWidth: 1,
        borderColor: Colors.grey.withOpacity(0.1),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: iconColor.withOpacity(0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(icon, color: iconColor, size: 20),
          ),
          const SizedBox(width: 8),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: const TextStyle(fontSize: 10, color: Colors.grey)),
                Text(
                  '\\$\${amount.toStringAsFixed(2)}',
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                    color: iconColor,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
`
  },
  {
    name: "add_transaction_dialog.dart",
    path: "lib/widgets/add_transaction_dialog.dart",
    language: "dart",
    content: `import 'package:flutter/material';
import 'package:cloud_firestore/cloud_firestore.dart';

class AddTransactionDialog extends StatefulWidget {
  final String userId;
  const AddTransactionDialog({super.key, required this.userId});

  @override
  State<AddTransactionDialog> createState() => _AddTransactionDialogState();
}

class _AddTransactionDialogState extends State<AddTransactionDialog> {
  final _formKey = GlobalKey<FormState>();
  final _merchantController = TextEditingController();
  final _amountController = TextEditingController();
  String _category = 'food';
  bool _isExpense = true;
  DateTime _selectedDate = DateTime.now();

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add Entry'),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // Switch
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ChoiceChip(
                    label: const Text('💸 Expense'),
                    selected: _isExpense,
                    onSelected: (val) => setState(() => _isExpense = true),
                  ),
                  ChoiceChip(
                    label: const Text('📈 Income'),
                    selected: !_isExpense,
                    onSelected: (val) => setState(() => _isExpense = false),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              
              // Amount field
              TextFormField(
                controller: _amountController,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(
                  labelText: 'Amount ($)',
                  prefixIcon: Icon(Icons.attach_money),
                  border: OutlineInputBorder(),
                ),
                validator: (val) {
                  if (val == null || val.isEmpty) return 'Enter an amount';
                  if (double.tryParse(val) == null) return 'Enter a valid number';
                  return null;
                },
              ),
              const SizedBox(height: 12),
              
              // Merchant field
              TextFormField(
                controller: _merchantController,
                decoration: InputDecoration(
                  labelText: _isExpense ? 'Merchant' : 'Income Source',
                  prefixIcon: const Icon(Icons.store),
                  border: const OutlineInputBorder(),
                ),
                validator: (val) => (val == null || val.isEmpty) ? 'Enter a name' : null,
              ),
              const SizedBox(height: 12),

              // Date Picker Field
              InkWell(
                onTap: () async {
                  final picked = await showDatePicker(
                    context: context,
                    initialDate: _selectedDate,
                    firstDate: DateTime(2020),
                    lastDate: DateTime(2100),
                  );
                  if (picked != null) {
                    setState(() => _selectedDate = picked);
                  }
                },
                child: InputDecorator(
                  decoration: const InputDecoration(
                    labelText: 'Transaction Date',
                    prefixIcon: Icon(Icons.calendar_today_outlined),
                    border: OutlineInputBorder(),
                  ),
                  child: Text(
                    "\${_selectedDate.year}-\${_selectedDate.month.toString().padLeft(2, '0')}-\${_selectedDate.day.toString().padLeft(2, '0')}",
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                ),
              ),
              const SizedBox(height: 12),
              
              // Category selector
              if (_isExpense)
                DropdownButtonFormField<String>(
                  value: _category,
                  decoration: const InputDecoration(
                    labelText: 'Category',
                    border: OutlineInputBorder(),
                  ),
                  items: const [
                    DropdownMenuItem(value: 'food', child: Text('🍔 Food & Dining')),
                    DropdownMenuItem(value: 'travel', child: Text('🚗 Transport')),
                    DropdownMenuItem(value: 'shopping', child: Text('🛍️ Shopping')),
                    DropdownMenuItem(value: 'bills', child: Text('💳 Bills & Utilities')),
                    DropdownMenuItem(value: 'other', child: Text('🌐 Other')),
                  ],
                  onChanged: (val) => setState(() => _category = val ?? 'other'),
                ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF0D9488),
            foregroundColor: Colors.white,
          ),
          onPressed: () async {
            if (_formKey.currentState!.validate()) {
              final amt = double.parse(_amountController.text);
              
              await FirebaseFirestore.instance
                  .collection('users')
                  .doc(widget.userId)
                  .collection('transactions')
                  .add({
                'merchant': _merchantController.text.trim(),
                'amount': amt,
                'category': _isExpense ? _category : 'other',
                'isExpense': _isExpense,
                'timestamp': FieldValue.serverTimestamp(),
                'date': "\${_selectedDate.year}-\${_selectedDate.month.toString().padLeft(2, '0')}-\${_selectedDate.day.toString().padLeft(2, '0')}",
              });
              
              if (mounted) Navigator.pop(context);
            }
          },
          child: const Text('Save Entry'),
        ),
      ],
    );
  }
}
`
  },
  {
    name: "profile_page.dart",
    path: "lib/pages/profile_page.dart",
    language: "dart",
    content: `import 'package:flutter/material';
import 'package:provider/provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../services/auth_service.dart';

class ProfilePage extends StatefulWidget {
  const ProfilePage({super.key});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  final _nameController = TextEditingController();
  final _budgetController = TextEditingController();
  bool _firestoreSync = true;
  bool _biometricLock = false;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    final authService = Provider.of<AuthService>(context, listen: false);
    _nameController.text = authService.currentUser?.displayName ?? 'Seenu';
    _loadUserProfile();
  }

  Future<void> _loadUserProfile() async {
    final authService = Provider.of<AuthService>(context, listen: false);
    final uid = authService.currentUser?.uid;
    if (uid != null) {
      final doc = await FirebaseFirestore.instance.collection('users').doc(uid).get();
      if (doc.exists) {
        final data = doc.data() as Map<String, dynamic>;
        setState(() {
          _budgetController.text = (data['dailyBudgetLimit'] ?? 150.0).toString();
          _firestoreSync = data['firestoreSync'] ?? true;
          _biometricLock = data['biometricLock'] ?? false;
        });
      }
    }
  }

  Future<void> _saveProfile() async {
    final authService = Provider.of<AuthService>(context, listen: false);
    final user = authService.currentUser;
    if (user != null) {
      setState(() => _isLoading = true);
      try {
        await user.updateDisplayName(_nameController.text.trim());
        await FirebaseFirestore.instance.collection('users').doc(user.uid).update({
          'displayName': _nameController.text.trim(),
          'dailyBudgetLimit': double.tryParse(_budgetController.text) ?? 150.0,
          'firestoreSync': _firestoreSync,
          'biometricLock': _biometricLock,
        });

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Profile synchronized with Firebase Firestore!'),
              backgroundColor: Color(0xFF0D9488),
            ),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: \\$e'), backgroundColor: Colors.red),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context);
    final email = authService.currentUser?.email ?? 'seenusreenivas388@gmail.com';

    return Scaffold(
      appBar: AppBar(
        title: const Text('My Profile', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(color: Color(0xFF0D9488)))
          : ListView(
              padding: const EdgeInsets.all(16.0),
              children: [
                Center(
                  child: Stack(
                    children: [
                      CircleAvatar(
                        radius: 45,
                        backgroundColor: const Color(0xFF0D9488).withOpacity(0.1),
                        child: Text(
                          _nameController.text.isNotEmpty ? _nameController.text[0].toUpperCase() : 'S',
                          style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Color(0xFF0D9488)),
                        ),
                      ),
                      Positioned(
                        bottom: 0,
                        right: 0,
                        child: Container(
                          padding: const EdgeInsets.all(4),
                          decoration: const BoxDecoration(
                            color: Colors.emerald,
                            shape: BoxShape.circle,
                          ),
                          child: const Icon(Icons.check, color: Colors.white, size: 14),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                const Text(
                  'ACCOUNT CREDENTIALS',
                  style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: Colors.grey, letterSpacing: 1.2),
                ),
                const SizedBox(height: 8),
                Card(
                  elevation: 0,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                    side: BorderSide(color: Colors.grey.withOpacity(0.1)),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      children: [
                        TextFormField(
                          controller: _nameController,
                          decoration: const InputDecoration(
                            labelText: 'Display Name',
                            prefixIcon: Icon(Icons.person_outline),
                            border: InputBorder.none,
                          ),
                        ),
                        const Divider(),
                        ListTile(
                          contentPadding: EdgeInsets.zero,
                          leading: const Icon(Icons.mail_outline),
                          title: const Text('Email Address', style: TextStyle(fontSize: 12, color: Colors.grey)),
                          subtitle: Text(email, style: const TextStyle(fontWeight: FontWeight.bold)),
                          trailing: Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            decoration: BoxDecoration(
                              color: Colors.emerald.withOpacity(0.1),
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: const Text('VERIFIED', style: TextStyle(fontSize: 10, color: Colors.emerald, fontWeight: FontWeight.bold)),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                const Text(
                  'SECURITY & DATABASE SETTINGS',
                  style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: Colors.grey, letterSpacing: 1.2),
                ),
                const SizedBox(height: 8),
                Card(
                  elevation: 0,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                    side: BorderSide(color: Colors.grey.withOpacity(0.1)),
                  ),
                  child: Column(
                    children: [
                      SwitchListTile(
                        value: _firestoreSync,
                        onChanged: (val) => setState(() => _firestoreSync = val),
                        title: const Text('Cloud Firestore Sync', style: TextStyle(fontWeight: FontWeight.bold)),
                        subtitle: const Text('Keep budget records synced across active devices', style: TextStyle(fontSize: 11)),
                        activeColor: const Color(0xFF0D9488),
                      ),
                      const Divider(height: 1),
                      SwitchListTile(
                        value: _biometricLock,
                        onChanged: (val) => setState(() => _biometricLock = val),
                        title: const Text('Biometric Lock Security', style: TextStyle(fontWeight: FontWeight.bold)),
                        subtitle: const Text('Require face ID or passcode when opening app', style: TextStyle(fontSize: 11)),
                        activeColor: const Color(0xFF0D9488),
                      ),
                      const Divider(height: 1),
                      Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: TextFormField(
                          controller: _budgetController,
                          keyboardType: TextInputType.number,
                          decoration: const InputDecoration(
                            labelText: 'Daily Alert Limit (\\$)',
                            prefixIcon: Icon(Icons.warning_amber_rounded),
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF0D9488),
                    foregroundColor: Colors.white,
                    minimumSize: const Size.fromHeight(50),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                  onPressed: _saveProfile,
                  child: const Text('SAVE PROFILE CHANGES', style: TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1.1)),
                ),
              ],
            ),
    );
  }
}
`
  },
  {
    name: "README.md",
    path: "README.md",
    language: "markdown",
    content: `# Daily Expense Pro (Flutter + Firebase)

A gorgeous premium fintech application built with Flutter & Firebase. Features Email Authentication, Real-time sync with Cloud Firestore, safety budget caps, and interactive in-app notifications.

## 🚀 Setup Instructions

Follow these step-by-step guidelines to launch the Flutter project on your local machine or device.

### 1. Prerequisites
- Install **Flutter SDK** (version >= 3.0.0): [Flutter Install Guide](https://docs.flutter.dev/get-started/install)
- Setup an editor like **VS Code** or **Android Studio** with the Flutter plugin.

### 2. Create local project directory
Create a new Flutter project in your workspace terminal:
\`\`\`bash
flutter create daily_expense_pro
cd daily_expense_pro
\`\`\`

### 3. Replace codebase files
Download all generated files from the companion exporter tab and overwrite the corresponding project paths:
- Replace \`pubspec.yaml\`
- Overwrite \`lib/main.dart\`
- Save \`lib/services/auth_service.dart\`
- Save \`lib/pages/dashboard_page.dart\`
- Save \`lib/widgets/add_transaction_dialog.dart\`

### 4. Connect to Firebase
To connect this app to your own Firebase project:
1. Go to the [Firebase Console](https://console.firebase.google.com/) and click **Create a Project**.
2. Install the **FlutterFire CLI** globally:
   \`\`\`bash
   dart pub global activate flutterfire_cli
   \`\`\`
3. Run the configuration tool in the project root:
   \`\`\`bash
   flutterfire configure
   \`\`\`
   This automatically connects your Android, iOS, and Web build configurations, and generates the required \`lib/firebase_options.dart\` file containing your production API keys.

### 5. Enable Firebase Services
In your Firebase Console, make sure to activate:
- **Firebase Authentication**: Go to Auth -> Sign-in Method -> Enable **Email/Password** provider.
- **Cloud Firestore Database**: Create a database, choose **Start in Test Mode** (or implement secure security rules).

### 6. Boot the Application!
Fetch the dependencies and run the application on your simulator/device:
\`\`\`bash
flutter pub get
flutter run
\`\`\`

Enjoy your professional, fully secure real-time Fintech wallet!
`
  }
];
