import { CategoryInfo, ThemeConfig, Transaction } from '../types';

export const CATEGORIES: Record<string, CategoryInfo> = {
  food: {
    id: 'food',
    label: 'Food & Dining',
    icon: 'Utensils',
    color: 'emerald',
    bgClass: 'bg-emerald-100 dark:bg-emerald-950/50',
    textClass: 'text-emerald-600 dark:text-emerald-400',
  },
  travel: {
    id: 'travel',
    label: 'Transport',
    icon: 'Car',
    color: 'blue',
    bgClass: 'bg-blue-100 dark:bg-blue-950/50',
    textClass: 'text-blue-600 dark:text-blue-400',
  },
  shopping: {
    id: 'shopping',
    label: 'Shopping',
    icon: 'ShoppingBag',
    color: 'rose',
    bgClass: 'bg-rose-100 dark:bg-rose-950/50',
    textClass: 'text-rose-600 dark:text-rose-400',
  },
  bills: {
    id: 'bills',
    label: 'Bills & Utilities',
    icon: 'ReceiptText',
    color: 'violet',
    bgClass: 'bg-violet-100 dark:bg-violet-950/50',
    textClass: 'text-violet-600 dark:text-violet-400',
  },
  other: {
    id: 'other',
    label: 'Other',
    icon: 'CircleEllipsis',
    color: 'slate',
    bgClass: 'bg-slate-100 dark:bg-slate-800/60',
    textClass: 'text-slate-600 dark:text-slate-400',
  },
};

export const THEME_CONFIGS: Record<string, ThemeConfig> = {
  teal: {
    id: 'teal',
    name: 'Teal Teal',
    primary: 'bg-teal-600 dark:bg-teal-500 hover:bg-teal-700 dark:hover:bg-teal-600 text-white',
    accentText: 'text-teal-600 dark:text-teal-400',
    accentBg: 'bg-teal-50 dark:bg-teal-950/30',
    gradient: 'from-teal-400 via-teal-500 to-cyan-600',
    glow: 'shadow-teal-500/20 dark:shadow-teal-400/10',
  },
  blue: {
    id: 'blue',
    name: 'Royal Blue',
    primary: 'bg-blue-600 dark:bg-blue-500 hover:bg-blue-700 dark:hover:bg-blue-600 text-white',
    accentText: 'text-blue-600 dark:text-blue-400',
    accentBg: 'bg-blue-50 dark:bg-blue-950/30',
    gradient: 'from-blue-500 via-indigo-500 to-violet-600',
    glow: 'shadow-blue-500/20 dark:shadow-blue-400/10',
  },
  emerald: {
    id: 'emerald',
    name: 'Mint Emerald',
    primary: 'bg-emerald-600 dark:bg-emerald-500 hover:bg-emerald-700 dark:hover:bg-emerald-600 text-white',
    accentText: 'text-emerald-600 dark:text-emerald-400',
    accentBg: 'bg-emerald-50 dark:bg-emerald-950/30',
    gradient: 'from-emerald-400 via-emerald-500 to-teal-600',
    glow: 'shadow-emerald-500/20 dark:shadow-emerald-400/10',
  },
  indigo: {
    id: 'indigo',
    name: 'Neon Indigo',
    primary: 'bg-indigo-600 dark:bg-indigo-500 hover:bg-indigo-700 dark:hover:bg-indigo-600 text-white',
    accentText: 'text-indigo-600 dark:text-indigo-400',
    accentBg: 'bg-indigo-50 dark:bg-indigo-950/30',
    gradient: 'from-indigo-500 via-purple-500 to-pink-600',
    glow: 'shadow-indigo-500/20 dark:shadow-indigo-400/10',
  },
  rose: {
    id: 'rose',
    name: 'Luxury Rose',
    primary: 'bg-rose-600 dark:bg-rose-500 hover:bg-rose-700 dark:hover:bg-rose-600 text-white',
    accentText: 'text-rose-600 dark:text-rose-400',
    accentBg: 'bg-rose-50 dark:bg-rose-950/30',
    gradient: 'from-rose-500 via-pink-500 to-orange-500',
    glow: 'shadow-rose-500/20 dark:shadow-rose-400/10',
  },
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    merchant: 'Whole Foods Market',
    amount: 34.20,
    category: 'food',
    time: '10:42 AM',
    date: '2026-07-08',
    isExpense: true,
  },
  {
    id: 't2',
    merchant: 'Uber Ride City Center',
    amount: 15.50,
    category: 'travel',
    time: '08:15 AM',
    date: '2026-07-08',
    isExpense: true,
  },
  {
    id: 't3',
    merchant: 'Apple One Subscription',
    amount: 22.95,
    category: 'bills',
    time: 'Yesterday',
    date: '2026-07-07',
    isExpense: true,
  },
  {
    id: 't4',
    merchant: 'Zara Fashion Studio',
    amount: 89.00,
    category: 'shopping',
    time: 'Yesterday',
    date: '2026-07-07',
    isExpense: true,
  },
  {
    id: 't5',
    merchant: 'Starbucks Coffee Corp',
    amount: 6.80,
    category: 'food',
    time: 'Jul 6, 2:14 PM',
    date: '2026-07-06',
    isExpense: true,
  },
  {
    id: 't6',
    merchant: 'Chevron Fuel Station',
    amount: 45.00,
    category: 'travel',
    time: 'Jul 5, 6:30 PM',
    date: '2026-07-05',
    isExpense: true,
  },
  {
    id: 't7',
    merchant: 'Client Freelance Payment',
    amount: 850.00,
    category: 'other',
    time: 'Jul 5, 9:00 AM',
    date: '2026-07-05',
    isExpense: false,
  },
];
